In [5]:
import random
import torch

In [7]:
def synthetic_data(w, b, num_examples):
    """生成y = Xw + b + 噪声。"""
    X = torch.normal(0, 1, (num_examples, len(w)))
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = synthetic_data(true_w, true_b, 1000)

In [8]:
import torch

# Set to print all elements
torch.set_printoptions(threshold=float('inf'))
print(features)

# Reset to default later if needed
torch.set_printoptions(threshold=1000)

tensor([[ 5.0203e-01, -3.8220e-01],
        [-6.0738e-01, -9.6954e-01],
        [-7.3545e-01,  2.9281e-01],
        [-1.1334e+00,  1.1422e+00],
        [-8.7591e-01,  4.6270e-01],
        [-1.5902e-01,  2.0043e-01],
        [-9.8352e-01,  5.0233e-01],
        [-2.2297e+00, -8.4876e-01],
        [-1.0387e+00,  5.5147e-01],
        [ 1.2302e+00,  1.5073e+00],
        [-9.1605e-02,  8.6157e-01],
        [ 4.4733e-01, -4.1668e-01],
        [-2.3862e+00, -1.8081e+00],
        [-1.1588e-01,  1.2622e+00],
        [-1.8377e-01, -8.3937e-01],
        [ 1.0315e+00, -2.4817e-01],
        [ 8.4798e-01, -4.9817e-01],
        [ 3.8146e-01,  9.4120e-01],
        [-5.1740e-01, -2.1260e-01],
        [-5.6541e-01,  1.7190e-01],
        [-6.3416e-01,  2.8917e-01],
        [-8.0819e-01,  9.0077e-03],
        [ 4.1406e-01,  2.6646e-01],
        [-1.1876e+00,  1.0325e-01],
        [-8.4323e-02, -2.9153e-01],
        [ 1.0543e-01,  3.3548e-01],
        [ 5.4241e-01,  7.2781e-01],
        [ 5.8739e-01,  4.256

In [9]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i:min(i + batch_size, num_examples)]
        )
        yield features[batch_indices], labels[batch_indices]

batch_size = 10
for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y) 
    break

tensor([[ 1.3961, -0.3600],
        [-0.1909,  1.6113],
        [-0.8085,  0.1864],
        [ 0.8270,  0.5747],
        [ 0.6965,  0.6029],
        [ 0.4347,  1.0884],
        [-0.4140,  1.4695],
        [-1.2755,  1.2330],
        [-0.3755, -1.0317],
        [ 0.1245,  3.1212]]) 
 tensor([[ 8.2219],
        [-1.6589],
        [ 1.9608],
        [ 3.9166],
        [ 3.5454],
        [ 1.3737],
        [-1.6194],
        [-2.5514],
        [ 6.9435],
        [-6.1673]])


# 定义初始化模型参数

In [10]:
w = torch.normal(0, 0.01, size=(2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# 定义模型

In [14]:
def linreg(X, w, b):
    """线性回归模型"""
    return troch.matmul(X, w) + b

# 定义损失函数

In [11]:
def squared_loss(y_hat, y):
    """均方损失"""
    return (y_hat - y.reshape(y_hat.shape))**2/2

# 定义优化算法

In [ ]:
def sgd(params, lr, batch_size):
    """小批量随机梯度下降"""
    with torch.no_grad():
        for param in params:
            param -= lr + param.grad / batch_size
            param.grad.zero_()
        